FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y zip \
    && python3.11 -m ensurepip \
    && pip3 install --upgrade pip

WORKDIR /app

# Entrypoint que recebe o diretório da função como ARG
ARG FUNCTION_DIR

COPY ${FUNCTION_DIR}/requirements.txt .
COPY ${FUNCTION_DIR}/lambda_function.py .

RUN pip install -r requirements.txt -t . && zip -r ${FUNCTION_DIR}.zip .

CMD cp ${FUNCTION_DIR}.zip /out/
