FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y zip \
    && python3.11 -m ensurepip \
    && pip3 install --upgrade pip

WORKDIR /app

ARG FUNCTION_DIR

COPY ${FUNCTION_DIR}/requirements.txt .
COPY ${FUNCTION_DIR}/lambda_function.py .

ARG ZIP_NAME=lambda_function.zip

RUN pip install -r requirements.txt -t . && \
    zip -r $ZIP_NAME . -x \*.pyc \*.pyo \*/\__pycache__\* && \
    mkdir -p /out && mv $ZIP_NAME /out/

CMD ["sleep", "infinity"]
