name: Terraform CI PR Dev → Homolog

on:
  pull_request:
    branches:
      - Homolog  # <- destino do PR (base branch)
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform:
    name: Validar Infraestrutura Terraform
    runs-on: ubuntu-latest

    if: github.head_ref == 'Dev'  # <- origem do PR (source branch)

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Validar formatação
        run: terraform fmt -check -recursive

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar sintaxe
        run: terraform validate

      - name: Gerar plano
        run: terraform plan -input=false
